version: '3'

services:
    app:
        build: .
        ports:
            - 8080:80
        volumes:
            - ./site/:/var/www/html
        links:
            - db:postgres
        

    db:
        image: postgres:9 # set version to 9 if you encounter problems.
        volumes:
            - ./docker/postgres/logs:/var/log/postgresql
            # - ./docker/postgres/datas:/var/lib/postgresql/data
            - /var/lib/postgresql/data
            - ./microgamezone.sql:/docker-entrypoint-initdb.d/microgamezone.sql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple-course
        #command: >
        #    bash -c "chmod -R 777 /var/lib/postgresql"

            
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres
            PGADMIN_DEFAULT_PASSWORD: changeme
            PG_DATABASE: simple-course
            PG_USER: postgres
            PG_PASSWORD: changeme
        volumes:
            - ./docker/pgadmin:/root/.pgadmin
        ports:
            - 8082:80
        links:
            - db:postgres

    angular_cli:
        image: trion/ng-cli:latest
        container_name: 'angular_cli'
        volumes:
            - ./site/microgamezone-front:/usr/app/
        working_dir: /usr/app/
        ports:
            - "4200:4200"
        command: >
          bash -c "npm install && ng serve --host 0.0.0.0"
